In [70]:
import numpy as np
import pandas as pd

send_mails = pd.read_csv("train.csv")

send_mails['time'] = (send_mails['EPA']*5 + send_mails['SPA']*3 + send_mails['RPA']*9)*send_mails['distance']

data = send_mails[['distance', 'EPA', 'SPA', 'RPA']][:120000]
classes = send_mails['time'][:120000]

from sklearn.model_selection import train_test_split as ttc

X_train, X_test, Y_train, Y_test = ttc(data.values, classes.values)

from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, Y_train)

clf.predict([[14.1350344888,0,1,0]])

from scipy.interpolate import interp1d
m = interp1d([0,50],[0,2])
m(42.30539277)

send_mails

        Unnamed: 0   distance  EPA  SPA  RPA        time
0                0   5.995637    0    1    0   17.986912
1                1   7.281727    0    1    0   21.845181
2                2   5.107735    0    1    0   15.323206
3                3   0.826957    0    1    0    2.480870
4                4  12.246472    0    1    0   36.739415
5                5  11.471052    0    1    0   34.413156
6                8   2.249577    0    1    0    6.748730
7                9   1.933646    0    1    0    5.800938
8               10   2.432364    0    1    0    7.297091
9               11  13.871406    0    1    0   41.614219
10              12  10.850700    0    1    0   32.552099
11              13  10.512985    0    1    0   31.538956
12              14   2.718395    0    1    0    8.155184
13              15   1.413042    0    1    0    4.239127
14              18  12.878949    0    1    0   38.636848
15              19   3.971495    0    1    0   11.914486
16              20   8.980959    0    1    0   26.942877
17              21   3.422736    0    1    0   10.268209
18              22   2.683586    0    1    0    8.050757
19              23   7.746302    0    1    0   23.238906
20              24   9.223305    0    1    0   27.669914
21              25   3.570859    0    1    0   10.712578
22              26  11.665622    0    1    0   34.996866
23              27  16.021885    0    1    0   48.065656
24              28   2.078013    0    1    0    6.234038
25              29   5.377615    0    1    0   16.132844
26              31  18.114933    0    1    0   54.344798
27              32   4.598183    0    1    0   13.794549
28              33  16.608853    0    1    0   49.826558
29              34   7.668316    0    1    0   23.004947
...            ...        ...  ...  ...  ...         ...
139942      145268   7.343435    0    0    1   66.090917
139943      145269   6.247470    0    0    1   56.227229
139944      145270   8.249338    0    0    1   74.244045
139945      145271   2.090989    0    0    1   18.818900
139946      145272  17.403925    0    0    1  156.635324
139947      145273  17.634254    0    0    1  158.708285
139948      145274  12.619167    0    0    1  113.572505
139949      145275   2.801484    0    0    1   25.213353
139950      145276   5.736048    0    0    1   51.624430
139951      145277  18.431746    0    0    1  165.885714
139952      145278   9.572360    0    0    1   86.151241
139953      145279  15.117346    0    0    1  136.056116
139954      145280  12.630404    0    0    1  113.673634
139955      145281  19.098893    0    0    1  171.890039
139956      145282   8.372109    0    0    1   75.348978
139957      145283  12.004608    0    0    1  108.041475
139958      145284   3.532831    0    0    1   31.795482
139959      145285  11.752652    0    0    1  105.773869
139960      145286   8.206958    0    0    1   73.862620
139961      145287  17.691009    0    0    1  159.219082
139962      145288  18.608433    0    0    1  167.475896
139963      145289   7.206670    0    0    1   64.860030
139964      145290  11.120548    0    0    1  100.084931
139965      145291   6.088275    0    0    1   54.794474
139966      145292  11.092388    0    0    1   99.831493
139967      145293   1.620401    0    0    1   14.583607
139968      145294   2.509671    0    0    1   22.587035
139969      145295  10.510520    0    0    1   94.594684
139970      145296   6.677075    0    0    1   60.093672
139971      145297  11.901860    0    0    1  107.116739

[139972 rows x 6 columns]